# Generated by Django 4.1 on 2022-08-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_reviewimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
