# Generated by Django 4.1 on 2022-08-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_comment_is_updated_review_comment_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="food_tags",
            field=models.ManyToManyField(related_name="review", to="review.foodtag"),
        ),
        migrations.DeleteModel(
            name="ReviewFoodTag",
        ),
    ]
