# Generated by Django 4.1 on 2022-08-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_introduction_tag_user_introduction_tags_and_more"),
        ("review", "0005_review_food_tags_delete_reviewfoodtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_likes",
            field=models.ManyToManyField(
                related_name="comments", through="user.UserCommentLike", to="user.user"
            ),
        ),
    ]
