# Generated by Django 4.1 on 2022-08-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_introduction_tag_user_introduction_tags_and_more"),
        ("review", "0006_comment_user_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user_bookmarks",
            field=models.ManyToManyField(
                related_name="bookmark_reviews", to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user_likes",
            field=models.ManyToManyField(related_name="like_reviews", to="user.user"),
        ),
        migrations.AlterField(
            model_name="review",
            name="food_tags",
            field=models.ManyToManyField(related_name="reviews", to="review.foodtag"),
        ),
    ]
