# Generated by Django 4.1 on 2022-09-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0008_alter_review_user_bookmarks_alter_review_user_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="review.product",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="review.retailer",
            ),
        ),
    ]
