# Generated by Django 4.1 on 2022-08-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userintroductiontag',
            old_name='tag',
            new_name='introduction_tag',
        ),
    ]
