# Generated by Django 4.1 on 2022-08-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_introduction_tag_delete_userintroductiontag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="introduction_tag",
        ),
        migrations.AddField(
            model_name="user",
            name="introduction_tags",
            field=models.ManyToManyField(
                related_name="users", to="user.introductiontag"
            ),
        ),
        migrations.AlterModelTable(
            name="usercommentlike",
            table="users_comment_likes",
        ),
    ]
