# Generated by Django 4.1 on 2022-08-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_introduction_tag_user_introduction_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usercommentlike",
            table="users_comments_likes",
        ),
        migrations.AlterModelTable(
            name="userreviewbookmark",
            table="users_reviews_bookmarks",
        ),
        migrations.AlterModelTable(
            name="userreviewlike",
            table="users_reviews_likes",
        ),
    ]
